nginx:
    build: docker/nginx
    ports:
        - "8081:80"
    volumes:
        - ./:/app
    links:
        - php

php:
    build: docker/php
    volumes:
        - ./:/app
    links:
        - mysql
        - rabbitmq
    working_dir: /app

mysql:
  image: mysql:5.7
  environment:
     - MYSQL_ROOT_PASSWORD=verysecret
     - MYSQL_DATABASE=fulfillment
     - MYSQL_USER=fulfiller
     - MYSQL_PASSWORD=fulfiller

rabbitmq:
    image: rabbitmq:3.6-management
    ports:
        - "15673:15672"
        - "5673:5672"
